// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KJhoP5_COunZcJ656P3SnujLpT021b4',
    appId: '1:185191729917:web:6558a660d06c1cecfc0c94',
    messagingSenderId: '185191729917',
    projectId: 'cleaner-3c67d',
    authDomain: 'cleaner-3c67d.firebaseapp.com',
    storageBucket: 'cleaner-3c67d.appspot.com',
    measurementId: 'G-T3XH48CSH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALKpL8iLEjzUGJIJNWW0oqhPgTX3yTq1U',
    appId: '1:185191729917:android:751044fc24cc82b1fc0c94',
    messagingSenderId: '185191729917',
    projectId: 'cleaner-3c67d',
    storageBucket: 'cleaner-3c67d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6jN9sT1srVSMdTyncErY63-8FDapfEAg',
    appId: '1:185191729917:ios:f5bb9cee27e462ebfc0c94',
    messagingSenderId: '185191729917',
    projectId: 'cleaner-3c67d',
    storageBucket: 'cleaner-3c67d.appspot.com',
    iosBundleId: 'com.example.cleaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6jN9sT1srVSMdTyncErY63-8FDapfEAg',
    appId: '1:185191729917:ios:f5bb9cee27e462ebfc0c94',
    messagingSenderId: '185191729917',
    projectId: 'cleaner-3c67d',
    storageBucket: 'cleaner-3c67d.appspot.com',
    iosBundleId: 'com.example.cleaner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2KJhoP5_COunZcJ656P3SnujLpT021b4',
    appId: '1:185191729917:web:68482d20dfedfe7afc0c94',
    messagingSenderId: '185191729917',
    projectId: 'cleaner-3c67d',
    authDomain: 'cleaner-3c67d.firebaseapp.com',
    storageBucket: 'cleaner-3c67d.appspot.com',
    measurementId: 'G-YSDXGN2TW5',
  );
}
