name: cleaner
description: "A CSOD & HOT initiative for a cleaner Jamaica"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
#  added
  flutter_native_splash: ^2.4.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  location_picker_flutter_map: ^3.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.7
  table_calendar: ^3.1.2
  open_route_service: ^1.2.4
  shared_preferences: ^2.0.7
#  flutter_secure_storage: ^5.0.2
#  multi_image_picker_view: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
